# MicroBrain OS

## Notebook 01

Running our first Small Language Model

Author: Abhayankar Bellur

Date:23-07-2026

# 1. Environment Setup

In [2]:
# =====================================================
# MicroBrain OS
# Notebook 01 - Environment Setup
# =====================================================

import os
import sys
import platform
import torch

print("=" * 60)
print("MicroBrain OS")
print("=" * 60)

print(f"Python Version : {sys.version}")
print(f"Operating System : {platform.system()}")
print(f"PyTorch Version : {torch.__version__}")

print("\nChecking GPU...")

if torch.cuda.is_available():
    print("GPU Available : YES")
    print(f"GPU Name : {torch.cuda.get_device_name(0)}")
    print(f"GPU Count : {torch.cuda.device_count()}")
else:
    print("GPU Available : NO")

print("=" * 60)

MicroBrain OS
Python Version : 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Operating System : Linux
PyTorch Version : 2.11.0+cu128

Checking GPU...
GPU Available : YES
GPU Name : Tesla T4
GPU Count : 1


# 2. Install Required Libraries

In [3]:
!pip install -q \
transformers \
accelerate \
sentence-transformers \
chromadb \
langchain \
langchain-community \
pymupdf \
python-docx \
bitsandbytes \
huggingface_hub

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/23.3 MB 91.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 94.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.7/25.7 MB 85.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 24.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 11.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 27.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 126.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 69.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.7/18.7 MB 94.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.2/137.2 kB 16.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60

Verification

In [1]:
import transformers
import chromadb
import sentence_transformers
import fitz

print("All libraries imported successfully.")

All libraries imported successfully.


# 3. Loading Our First Small Language Model (SLM)

In [2]:
from huggingface_hub import notebook_login

In [3]:
from huggingface_hub import notebook_login

notebook_login()

In [4]:
from huggingface_hub import whoami

print(whoami())

{'type': 'user', 'id': '6a621f22872a1f6ff419a73f', 'name': 'abhibellur', 'fullname': 'Abhayankar Bellur', 'canPay': False, 'billingMode': 'prepaid', 'periodEnd': 1785542400, 'isPro': False, 'avatarUrl': '/avatars/fdb152e22bc6bb3dc4f205f8c7bb668a.svg', 'orgs': [], 'auth': {'type': 'oauth', 'expiresAt': '2026-08-22T14:11:42.000Z'}}


# 4. Loading Our First Small Language Model

In [5]:
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM
)

import torch

In [6]:
MODEL_NAME = "Qwen/Qwen2.5-0.5B-Instruct"

print(MODEL_NAME)

Qwen/Qwen2.5-0.5B-Instruct


In [7]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

print("Tokenizer Loaded Successfully")

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

Tokenizer Loaded Successfully


In [8]:
print(type(tokenizer))

<class 'transformers.models.qwen2.tokenization_qwen2.Qwen2Tokenizer'>


# 5. Loading the SLM into GPU Memory

In [9]:
gpu = torch.cuda.get_device_properties(0)

print("="*60)

print("GPU Information")

print("="*60)

print(f"Name : {gpu.name}")

print(f"Total Memory : {gpu.total_memory/1024**3:.2f} GB")

print(f"Multiprocessors : {gpu.multi_processor_count}")

print("="*60)

GPU Information
Name : Tesla T4
Total Memory : 14.56 GB
Multiprocessors : 40


In [10]:
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    device_map="auto"
)

print("Model Loaded Successfully")

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!


model.safetensors: reconstructing file:   0%|          |  0.00B /  988MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Model Loaded Successfully


# 6. Our First Inference

In [11]:
prompt = """
What is Artificial Intelligence?
"""

In [12]:
inputs = tokenizer(prompt, return_tensors="pt")

In [13]:
print(inputs)

{'input_ids': tensor([[  198,  3838,   374, 58194, 21392,  5267]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1]])}


In [14]:
print(tokenizer.decode(inputs["input_ids"][0]))


What is Artificial Intelligence?



# 7. Running Our First Inference

In [15]:
inputs = tokenizer(
    prompt,
    return_tensors="pt"
)

inputs = inputs.to(model.device)

print(f"Model Device : {model.device}")
print(f"Input Device : {inputs['input_ids'].device}")

Model Device : cuda:0
Input Device : cuda:0


In [16]:
with torch.no_grad():

    outputs = model.generate(
        **inputs,
        max_new_tokens=150,
        temperature=0.7,
        do_sample=True
    )

In [17]:
response = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print(response)


What is Artificial Intelligence?
Artificial intelligence (AI) refers to the simulation of human intelligence in machines. This includes tasks that normally require human cognition, such as perception and learning. AI can be used for a wide range of applications, from simple tasks like recognizing faces or playing games, to more complex ones like autonomous vehicles or natural language processing.
Some common examples of artificial intelligence include:

  * Machine learning algorithms used in self-driving cars
  * Natural language processing used in chatbots and virtual assistants
  * Image recognition software used in security systems and medical imaging

AI has many potential benefits, including increased efficiency, cost savings, and improved decision-making. However, it also raises concerns about job displacement and privacy issues.

Is AI safe?
As with any technology, there


# 8. Inspecting Our First SLM

In [18]:
print(model)

Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(151936, 896)
    (layers): ModuleList(
      (0-23): 24 x Qwen2DecoderLayer(
        (self_attn): Qwen2Attention(
          (q_proj): Linear(in_features=896, out_features=896, bias=True)
          (k_proj): Linear(in_features=896, out_features=128, bias=True)
          (v_proj): Linear(in_features=896, out_features=128, bias=True)
          (o_proj): Linear(in_features=896, out_features=896, bias=False)
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=896, out_features=4864, bias=False)
          (up_proj): Linear(in_features=896, out_features=4864, bias=False)
          (down_proj): Linear(in_features=4864, out_features=896, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((896,), eps=1e-06)
    (rotary_emb): Qwen2

In [19]:
print(type(model))

<class 'transformers.models.qwen2.modeling_qwen2.Qwen2ForCausalLM'>


In [20]:
print(model.config)

Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "float16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_t

In [21]:
print(f"Vocabulary Size : {model.config.vocab_size}")

print(f"Hidden Size : {model.config.hidden_size}")

print(f"Layers : {model.config.num_hidden_layers}")

print(f"Attention Heads : {model.config.num_attention_heads}")

print(f"Max Position Embeddings : {model.config.max_position_embeddings}")

Vocabulary Size : 151936
Hidden Size : 896
Layers : 24
Attention Heads : 14
Max Position Embeddings : 32768


# 9. Understanding Embeddings

In [22]:
embedding_layer = model.model.embed_tokens

print(embedding_layer)

Embedding(151936, 896)


In [23]:
embedding_weights = embedding_layer.weight

print(embedding_weights.shape)

torch.Size([151936, 896])


In [24]:
print(f"Shape : {embedding_weights.shape}")

print(f"Total Parameters : {embedding_weights.numel():,}")

print(f"Memory : {embedding_weights.numel()*2/1024/1024:.2f} MB")

Shape : torch.Size([151936, 896])
Total Parameters : 136,134,656
Memory : 259.66 MB


In [25]:
word = "dog"

In [26]:
tokens = tokenizer(word)

print(tokens)

{'input_ids': [18457], 'attention_mask': [1]}


In [27]:
token_id = tokens["input_ids"][0]

vector = embedding_weights[token_id]

print(vector.shape)

torch.Size([896])


In [28]:
print(vector[:20])

tensor([-0.0092, -0.0031,  0.0066, -0.0211,  0.0035,  0.0208, -0.0219,  0.0361,
         0.0093, -0.0017, -0.0081,  0.0052, -0.0071,  0.0020,  0.0308,  0.0129,
        -0.0056,  0.0146, -0.0051, -0.0184], device='cuda:0',
       dtype=torch.float16, grad_fn=<SliceBackward0>)


In [29]:
words = [
    "dog",
    "cat",
    "computer",
    "law"
]

In [30]:
for word in words:

    token = tokenizer(word)["input_ids"][0]

    vector = embedding_weights[token]

    print(word)

    print(vector[:10])

    print()

dog
tensor([-0.0092, -0.0031,  0.0066, -0.0211,  0.0035,  0.0208, -0.0219,  0.0361,
         0.0093, -0.0017], device='cuda:0', dtype=torch.float16,
       grad_fn=<SliceBackward0>)

cat
tensor([-0.0137,  0.0031, -0.0033, -0.0068, -0.0227,  0.0194, -0.0143,  0.0410,
        -0.0095,  0.0047], device='cuda:0', dtype=torch.float16,
       grad_fn=<SliceBackward0>)

computer
tensor([-0.0112,  0.0160,  0.0121,  0.0085, -0.0007,  0.0091, -0.0018,  0.0217,
        -0.0208,  0.0110], device='cuda:0', dtype=torch.float16,
       grad_fn=<SliceBackward0>)

law
tensor([-0.0040, -0.0056, -0.0001, -0.0310,  0.0035,  0.0171, -0.0030,  0.0222,
         0.0066, -0.0002], device='cuda:0', dtype=torch.float16,
       grad_fn=<SliceBackward0>)



In [31]:
import torch.nn.functional as F

In [34]:
dog = get_embedding("dog")
cat = get_embedding("cat")
car = get_embedding("car")
law = get_embedding("law")

print("dog-cat")

print(
    F.cosine_similarity(
        dog.unsqueeze(0),
        cat.unsqueeze(0)
    )
)

print("dog-law")

print(
    F.cosine_similarity(
        dog.unsqueeze(0),
        law.unsqueeze(0)
    )
)

dog-cat
tensor([0.2637], device='cuda:0', dtype=torch.float16, grad_fn=<SumBackward1>)
dog-law
tensor([0.1497], device='cuda:0', dtype=torch.float16, grad_fn=<SumBackward1>)


In [35]:
total_params = sum(p.numel() for p in model.parameters())

trainable_params = sum(
    p.numel()
    for p in model.parameters()
    if p.requires_grad
)

print(f"Total Parameters : {total_params:,}")

print(f"Trainable Parameters : {trainable_params:,}")

Total Parameters : 494,032,768
Trainable Parameters : 494,032,768


In [36]:
for name, parameter in model.named_parameters():

    print(
        name,
        parameter.shape
    )

model.embed_tokens.weight torch.Size([151936, 896])
model.layers.0.self_attn.q_proj.weight torch.Size([896, 896])
model.layers.0.self_attn.q_proj.bias torch.Size([896])
model.layers.0.self_attn.k_proj.weight torch.Size([128, 896])
model.layers.0.self_attn.k_proj.bias torch.Size([128])
model.layers.0.self_attn.v_proj.weight torch.Size([128, 896])
model.layers.0.self_attn.v_proj.bias torch.Size([128])
model.layers.0.self_attn.o_proj.weight torch.Size([896, 896])
model.layers.0.mlp.gate_proj.weight torch.Size([4864, 896])
model.layers.0.mlp.up_proj.weight torch.Size([4864, 896])
model.layers.0.mlp.down_proj.weight torch.Size([896, 4864])
model.layers.0.input_layernorm.weight torch.Size([896])
model.layers.0.post_attention_layernorm.weight torch.Size([896])
model.layers.1.self_attn.q_proj.weight torch.Size([896, 896])
model.layers.1.self_attn.q_proj.bias torch.Size([896])
model.layers.1.self_attn.k_proj.weight torch.Size([128, 896])
model.layers.1.self_attn.k_proj.bias torch.Size([128])
mo